mod.id = "template"
mod.name = "Template Project"
mod.group = "site.siredvin.template"
mod.version = "0.1.0"
mod.license = "MIT"
mod.authors = "Edvin"
mod.description = "A minimal Stonecutter multiversion mod template."

deps.fabric_loader = "0.17.2"
loomx.loom_version = "1.17.12"

[fabric."1.20.1"]
mod.mc_compat = ">=1.20.1 <1.21"
deps.fabric_api = "0.92.6+1.20.1"

[forge."1.20.1"]
mod.mc_compat = "[1.20.1,1.21)"
deps.forge_loader = "47.3.39"

[fabric."1.21.1"]
mod.mc_compat = ">=1.21 <=1.21.1"
deps.fabric_api = "0.116.12+1.21.1"

[neoforge."1.21.1"]
mod.mc_compat = "[1.21,1.21.2)"
deps.neoforge_loader = "21.1.234"
