modLoader="javafml"
loaderVersion="[47,)"
license="${license}"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="${authors}"
description='''${description}'''

[[dependencies.${id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft}"
ordering="NONE"
side="BOTH"
