modLoader="javafml"
loaderVersion="[1,)"
license="${license}"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="${authors}"
description='''${description}'''

[[dependencies.${id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
ordering="NONE"
side="BOTH"
